use_frameworks!

platform :ios, '8.0'

target 'ZMJNoDataView_Example' do
  pod 'ZMJNoDataView', :path => '../'

  target 'ZMJNoDataView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
